#!/usr/bin/env bash

if test -f ./conscribo.yml; then
    echo "Applying conscribo.yml..."
    kubectl apply -f ./conscribo.yml
else
    echo "Skipping missing conscribo.yml..."
fi

if test -f ./messagebird.yml; then
    echo "Applying messagebird.yml..."
    kubectl apply -f ./messagebird.yml
else
    echo "Skipping missing messagebird.yml..."
fi
