steps:
  # Build the container image via Kaniko cache
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --destination=gcr.io/$PROJECT_ID/e-voting:$BRANCH_NAME
      - --destination=gcr.io/$PROJECT_ID/e-voting:$BRANCH_NAME-$SHORT_SHA
      - --cache=true
      - --cache-ttl=48h

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - gcr.io/$PROJECT_ID/e-voting:$BRANCH_NAME
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - gcr.io/$PROJECT_ID/e-voting:$BRANCH_NAME-$SHORT_SHA

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --image=gcr.io/$PROJECT_ID/e-voting:$BRANCH_NAME-$SHORT_SHA
      - --region=europe-west4
      - --platform=managed

substitutions:
  _SERVICE_NAME: e-voting
tags:
  - github
  - branch:$BRANCH_NAME
  - commit:$SHORT_SHA
images:
  - gcr.io/$PROJECT_ID/e-voting:$BRANCH_NAME-$SHORT_SHA
  - gcr.io/$PROJECT_ID/e-voting:$BRANCH_NAME
