name: "Deploy application"

on:
  release:
    types:
      - published

env:
  # Docker tags
  RELEASE_TAG: ${{ github.event.release.tag_name }}
  RELEASE_HASH: ${{ github.sha }}

  # Google Container Repository values
  PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
  SERVICE: evoting
  GCR_REGION: eu

  # Terraform values
  TF_VAR_project: ${{ secrets.GOOGLE_PROJECT_ID }}
  TF_VAR_container_name: evoting
  TF_VAR_container_version:  ${{ github.sha }}
  TF_VAR_container_region: eu
  TF_VAR_app_prefix: vote2021-release

  # Dummy app key
  APP_KEY: base64:8fzvICpJu/KQi7u4kP59hU6stPTYDSx+ftkyR2z5do0=

jobs:
  build-frontend:
    name: "Build application front-end"
    runs-on: "ubuntu-latest"

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: '8.0'
          extensions: json, mbstring, dom, fileinfo, mysql
          coverage: none

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node dependencies
        run: npm clean-install

      - name: Build Front-end
        run: npm run-script build

      - name: Copy environment config
        run: cp .github/actions.env .env

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v1
        with:
          composer-options: "--ignore-platform-req=php --no-dev"

      - name: Create Docker error files
        run: php artisan docker:prepare-pages

      - name: Publish front-end
        uses: actions/upload-artifact@v2
        with:
          name: frontend
          path: |
            public/css
            public/images
            public/js
            public/mix-manifest.json

  build-github-image:
    name: "Build Docker image for GitHub"
    runs-on: ubuntu-latest
    needs:
      - build-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download front-end
        uses: actions/download-artifact@v2
        with:
          name: frontend
          path: public/

      - name: Build image for GitHub
        run: |
          docker build \
            --tag docker.pkg.github.com/gumbo-millennium/e-voting/app:${RELEASE_HASH} \
            --tag docker.pkg.github.com/gumbo-millennium/e-voting/app:${RELEASE_TAG} \
            --tag docker.pkg.github.com/gumbo-millennium/e-voting/app:latest \
            --file .cloud/Dockerfile \
            --progress plain \
            --target main \
            .

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push newly created tag
        run: |
          docker push docker.pkg.github.com/gumbo-millennium/e-voting/app:${RELEASE_HASH}
          docker push docker.pkg.github.com/gumbo-millennium/e-voting/app:${RELEASE_TAG}
          docker push docker.pkg.github.com/gumbo-millennium/e-voting/app:latest

  build-gcr-image:
    name: "Build Docker image for Google Container Registry"
    runs-on: ubuntu-latest
    needs:
      - build-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download front-end
        uses: actions/download-artifact@v2
        with:
          name: frontend
          path: public/

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build Google Cloud Run image
        run: |
          docker build \
            --tag ${GCR_REGION}.gcr.io/${PROJECT_ID}/${SERVICE}:${RELEASE_HASH} \
            --tag ${GCR_REGION}.gcr.io/${PROJECT_ID}/${SERVICE}:${RELEASE_TAG} \
            --tag ${GCR_REGION}.gcr.io/${PROJECT_ID}/${SERVICE}:latest \
            --file .cloud/Dockerfile \
            --progress plain \
            --target google-cloud-run \
            .

      - name: Push image to Google Container Registry
        run: |
          docker push ${GCR_REGION}.gcr.io/${PROJECT_ID}/${SERVICE}:${RELEASE_HASH}
          docker push ${GCR_REGION}.gcr.io/${PROJECT_ID}/${SERVICE}:${RELEASE_TAG}
          docker push ${GCR_REGION}.gcr.io/${PROJECT_ID}/${SERVICE}:latest

  deploy-terraform:
    name: "Deploy Terraform application"
    runs-on: ubuntu-latest
    environment: production
    needs:
      - build-gcr-image

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true

      - name: Register Google Application Credentials in env
        run: echo "TF_VAR_credentials_file=${GOOGLE_APPLICATION_CREDENTIALS}" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLI_TOKEN }}

      - name: Validate Terraform formatting
        run: terraform -chdir=.cloud/terraform fmt -check

      - name: Initialize Terraform
        run: terraform -chdir=.cloud/terraform init -input=false

      - name: Validate Terraform configuration
        run: terraform -chdir=.cloud/terraform validate

      - name: Refresh Terraform deployment information
        run: terraform -chdir=.cloud/terraform refresh

      - name: Plan Terraform deployment
        run: terraform -chdir=.cloud/terraform plan -out ./terraform.tfplan > /dev/null

      - name: Apply Terraform deployment
        run: terraform -chdir=.cloud/terraform apply ./terraform.tfplan
